# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'WordRecognition' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WordRecognition
  pod 'TesseractOCRiOS', '~>4.0'

  target 'WordRecognitionTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WordRecognitionUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
